bump_version: null
lint: {}
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Phuong Le
  description: postprocessing of LCMB data
  force: true
  is_nfcore: true
  name: lcmb
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0.0dev
update: null
